version: '3.0'

services:
  main:
    container_name: main
    hostname: main
    build:
      context: .
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: ilau020203
      POSTGRES_HOST: postgres
      POSTGRES_USER: ilau
      POSTGRESS_PORT: 5432
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
